# Generated by Django 4.2.1 on 2023-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoounts', '0003_alter_customuser_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='job',
            field=models.CharField(default='No job', max_length=100),
        ),
    ]
